# K-Nearest Neighbors

1. you move to a new city and want to decide whether a resturant is good?
2. How?
3. Check review
4. Ask nearby people
5. see what friends recommendations
6. KNN also ask its nearest neighbors before making a prediction.

2. K-Nearest neighbors (KNN) is a supervised machine learning algorithm
- Used for:
 - Classification 
 - Regression
- It predicts the output by loading at the K nearest data points.

- **Example**
  - A new student join a class.
    - Nearby student
      - A-> Science
      - B -> Science 
      - C-> Commerce
    - predict -> commerce
- **Example2**
   - Movie Recommendation
   - Himank-> Action
   - Mihika -> Thriller
   - Shaurya -> Action
   - Saurab-> Action

# Where KNN is Used: 
  - Email spam detection
  - Disease prediction
  - Student will pass or not
  - Banking(Credit approval)
  - face recognition

# Types Of Problems solved
 - 1. Classification-:
    - output is category
    - ex->> spam or not spam
    - cancer or No cancer
    - male or female

- 2. Regression:
   - Output is continuous value
   - ex->> House price
   - Salary prediction
   - temperature predict

- 3. why??
   - suppose there is a new point
   - there are many old points
   - the closed one
   - because nearby objects usually have similar properties.

- 4. Distance Measure ..............??
   - Eucludiean
   - d= sqrt((x2-x1))^2 +((y2-y1)^2)
   - point A - (2,3)
   - point b - (5,7)
   - Distance = sqrt((5-2)^2 + (7-3)^2) = 9+ 16 =25 ->> 5


- 5. Manhattan Distance
    - like walking on road
    - can not move diagonally
    - form = |x2-x1| + |y2- y1|

- 6. Hamming Distance
    - used for categorical data
    - Binary Data
    - ex ->> 1011110 ->> 10011
    - Different bits = Hamming disatnce

- K means number of nearest neighbors
   - K =3 : Look at nearest 3 neighbors
   - K=5: Look at nearest 5 neighbors

- Example:
  - Suppose : red,red, blue, k=3
  - majority: red
  - predict : red

4. Choosing K?
 - small k:
 - advantage: sensitive,captures local pattern
 - disadvantages: Overfitting, Noise affects prediction

- Large K:
   - advantage:Stable, Less noise
   - disadvantage : Underfitting

- IMP: Golden rules:
- K = sqrt(N)
- N: No. of samples
- examples : 100 samples = sqrt(N) = sqrt(100) =10
-K =10, then use cross validation to choose the best K

# Working
1. Choose K
2. Calculate Distance
3. Find K nearest neighbors
4. Voting
5. predict our class

- Suppose K= 3
- neighbor : A
- neighbor : B
- neighbor : A
- neighbor : C
- Predict A

2. Neighbors: cat
   Neighbors: Dog 
   Neighbors: Dog
   Neighbors: Dog
   - Predict : Dog

# Dataset
- height: 160,165,170,180,185
- weight: 55,60,65,90,95
- class:  fit,fit,fit,unfit,unfit

- New Person:
- height is 172
- weight is 68
- class? fit ya unfit??

- predict: Fit

# Feature Scalling?

- age: 20
- salary: 20000
- which salary feature dominates
- salary
- Therefore always scale data before KNN

# KNN Lazy learner or fast learner?? Why??

KNN is Lazy learner because -:
- because it does not learn during training
- it stores data and predicts only when a sample arrives

# KNN :
- Lazy learner, it does not requires training, and it works on distance based so slow prediction.

# Logistic Regression
 - Eager learner, it requires a training and it is based on probability and fast prediction.

## Practice

#### Workflow

 - Import libraries
 - Load dataset
 - Explore dataset
 - Split feature and target
 - train-test split
 - feature scaling
 - create KNN model
 - Train model
 - Prediction
 - Evaluate model
 - (Accuracy, Precision Recall, f1 Score, classification_report)
 - Predict New Data
 - find best K value

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score,precision_score, recall_score, f1_score

In [3]:
cancer = load_breast_cancer()

In [5]:
df=pd.DataFrame(
    cancer.data,
    columns= cancer.feature_names
)

In [6]:
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:
df['Target'] = cancer.target

In [8]:
df.head(10)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,Target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0
5,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,0.2087,0.07613,...,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440,0
6,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,0.1794,0.05742,...,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368,0
7,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,0.2196,0.07451,...,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.1556,0.3196,0.11510,0
8,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,0.2350,0.07389,...,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.2060,0.4378,0.10720,0
9,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,0.2030,0.08243,...,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.2210,0.4366,0.20750,0

In [9]:
df.shape

(569, 31)

In [10]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
Target                     0
dtype: int64

In [11]:
print(df['Target'].value_counts())

Target
1    357
0    212
Name: count, dtype: int64

In [ ]:
x= df.drop('Target',axis=1) # Independent variable also called feature
y= df['Target'] # Depenndent variable also called target variable

In [13]:
x_train,x_test,y_train,y_test= train_test_split(
    x,y,
    test_size=0.2,
    random_state = 42
)